-- =====================================================================
--  Random placeholder addresses (street detail + ward) for the 210 HCMC
--  archdiocese parishes added in V8, which had no address data in their
--  source. province is set to the known-correct 'TP. Ho Chi Minh' for
--  all of them (not randomized - that much is actually known); address
--  and ward are randomly generated placeholders, explicitly requested
--  as such, not real data.
-- =====================================================================

UPDATE parishes SET address = '164 Pasteur', province = 'TP. Hồ Chí Minh', ward = 'Bến Thành' WHERE slug = 'an-binh';
UPDATE parishes SET address = '190 Quang Trung', province = 'TP. Hồ Chí Minh', ward = 'Thạnh Mỹ Lợi' WHERE slug = 'an-lac';
UPDATE parishes SET address = '58 Nam Kỳ Khởi Nghĩa', province = 'TP. Hồ Chí Minh', ward = 'Nguyễn Thái Bình' WHERE slug = 'an-nhon';
UPDATE parishes SET address = '174 Tô Ký', province = 'TP. Hồ Chí Minh', ward = 'Cầu Ông Lãnh' WHERE slug = 'an-phu';
UPDATE parishes SET address = '152 Phạm Ngũ Lão', province = 'TP. Hồ Chí Minh', ward = 'Đa Kao' WHERE slug = 'an-phu-2';
UPDATE parishes SET address = '8 Điện Biên Phủ', province = 'TP. Hồ Chí Minh', ward = 'Bình Trưng Tây' WHERE slug = 'an-thoi-dong';
UPDATE parishes SET address = '60 Nguyễn Ảnh Thủ', province = 'TP. Hồ Chí Minh', ward = 'Bến Thành' WHERE slug = 'anton';
UPDATE parishes SET address = '144 Hoàng Văn Thụ', province = 'TP. Hồ Chí Minh', ward = 'Tân Sơn Hòa' WHERE slug = 'anton-cau-ong-lanh';
UPDATE parishes SET address = '108 Nguyễn Văn Trỗi', province = 'TP. Hồ Chí Minh', ward = 'Hóc Môn' WHERE slug = 'ba-diem';
UPDATE parishes SET address = '151 Quang Trung', province = 'TP. Hồ Chí Minh', ward = 'Bến Nghé' WHERE slug = 'ba-thon';
UPDATE parishes SET address = '195 Trần Hưng Đạo', province = 'TP. Hồ Chí Minh', ward = 'Gò Vấp' WHERE slug = 'bac-ai';
UPDATE parishes SET address = '88 Quang Trung', province = 'TP. Hồ Chí Minh', ward = 'An Phú' WHERE slug = 'bac-dung';
UPDATE parishes SET address = '56 Tôn Đức Thắng', province = 'TP. Hồ Chí Minh', ward = 'Nguyễn Thái Bình' WHERE slug = 'bac-ha';
UPDATE parishes SET address = '24 Đồng Khởi', province = 'TP. Hồ Chí Minh', ward = 'Nguyễn Thái Bình' WHERE slug = 'bach-dang';
UPDATE parishes SET address = '92 Nguyễn Công Trứ', province = 'TP. Hồ Chí Minh', ward = 'Phú Hữu' WHERE slug = 'ban-co';
UPDATE parishes SET address = '207 Hai Bà Trưng', province = 'TP. Hồ Chí Minh', ward = 'Bình Chánh' WHERE slug = 'ben-cat';
UPDATE parishes SET address = '138 Pasteur', province = 'TP. Hồ Chí Minh', ward = 'Phú Nhuận' WHERE slug = 'ben-hai';
UPDATE parishes SET address = '21 Lê Đức Thọ', province = 'TP. Hồ Chí Minh', ward = 'Trường Thạnh' WHERE slug = 'binh-an';
UPDATE parishes SET address = '213 Lũy Bán Bích', province = 'TP. Hồ Chí Minh', ward = 'Phước Long' WHERE slug = 'binh-an-thuong';
UPDATE parishes SET address = '148 Hoàng Văn Thụ', province = 'TP. Hồ Chí Minh', ward = 'Cầu Kho' WHERE slug = 'binh-chanh';
UPDATE parishes SET address = '12 Lạc Long Quân', province = 'TP. Hồ Chí Minh', ward = 'Cát Lái' WHERE slug = 'binh-chieu';
UPDATE parishes SET address = '198 Lê Văn Sỹ', province = 'TP. Hồ Chí Minh', ward = 'Cầu Ông Lãnh' WHERE slug = 'binh-dong';
UPDATE parishes SET address = '219 Nguyễn Văn Trỗi', province = 'TP. Hồ Chí Minh', ward = 'Nguyễn Thái Bình' WHERE slug = 'binh-hoa';
UPDATE parishes SET address = '98 Quang Trung', province = 'TP. Hồ Chí Minh', ward = 'Bình Chánh' WHERE slug = 'binh-hung';
UPDATE parishes SET address = '163 Hàm Nghi', province = 'TP. Hồ Chí Minh', ward = 'An Khánh' WHERE slug = 'binh-loi';
UPDATE parishes SET address = '95 Nguyễn Công Trứ', province = 'TP. Hồ Chí Minh', ward = 'Bình Trưng Tây' WHERE slug = 'binh-minh';
UPDATE parishes SET address = '172 Quang Trung', province = 'TP. Hồ Chí Minh', ward = 'Cầu Kho' WHERE slug = 'binh-phuoc';
UPDATE parishes SET address = '156 Lũy Bán Bích', province = 'TP. Hồ Chí Minh', ward = 'An Khánh' WHERE slug = 'binh-son';
UPDATE parishes SET address = '137 Cộng Hòa', province = 'TP. Hồ Chí Minh', ward = 'An Khánh' WHERE slug = 'binh-thai';
UPDATE parishes SET address = '119 Đồng Khởi', province = 'TP. Hồ Chí Minh', ward = 'Long Trường' WHERE slug = 'binh-tho';
UPDATE parishes SET address = '237 Lũy Bán Bích', province = 'TP. Hồ Chí Minh', ward = 'Cát Lái' WHERE slug = 'binh-thoi';
UPDATE parishes SET address = '176 Võ Thị Sáu', province = 'TP. Hồ Chí Minh', ward = 'Tân Định' WHERE slug = 'binh-thuan';
UPDATE parishes SET address = '59 Hai Bà Trưng', province = 'TP. Hồ Chí Minh', ward = 'Long Bình' WHERE slug = 'binh-thuan-2';
UPDATE parishes SET address = '103 Quang Trung', province = 'TP. Hồ Chí Minh', ward = 'Cầu Kho' WHERE slug = 'binh-xuyen';
UPDATE parishes SET address = '55 Phan Văn Trị', province = 'TP. Hồ Chí Minh', ward = 'Long Bình' WHERE slug = 'bui-mon';
UPDATE parishes SET address = '55 Âu Cơ', province = 'TP. Hồ Chí Minh', ward = 'Tân Quý' WHERE slug = 'bui-phat';
UPDATE parishes SET address = '102 Âu Cơ', province = 'TP. Hồ Chí Minh', ward = 'Bình Chánh' WHERE slug = 'can-gio';
UPDATE parishes SET address = '37 Trường Chinh', province = 'TP. Hồ Chí Minh', ward = 'Thảo Điền' WHERE slug = 'cao-thai';
UPDATE parishes SET address = '64 Lê Đức Thọ', province = 'TP. Hồ Chí Minh', ward = 'Tân Sơn Hòa' WHERE slug = 'cau-kho';
UPDATE parishes SET address = '68 Nguyễn Oanh', province = 'TP. Hồ Chí Minh', ward = 'Gò Vấp' WHERE slug = 'cau-lon';
UPDATE parishes SET address = '230 Nguyễn Oanh', province = 'TP. Hồ Chí Minh', ward = 'Tân Sơn Nhì' WHERE slug = 'chanh-hung';
UPDATE parishes SET address = '93 Nguyễn Văn Trỗi', province = 'TP. Hồ Chí Minh', ward = 'Thảo Điền' WHERE slug = 'duc-ba-chanh-toa-sai-gon';
UPDATE parishes SET address = '131 Phạm Văn Đồng', province = 'TP. Hồ Chí Minh', ward = 'Cầu Ông Lãnh' WHERE slug = 'chau-binh';
UPDATE parishes SET address = '194 Nguyễn Trãi', province = 'TP. Hồ Chí Minh', ward = 'Cô Giang' WHERE slug = 'chau-nam';
UPDATE parishes SET address = '40 Lũy Bán Bích', province = 'TP. Hồ Chí Minh', ward = 'An Khánh' WHERE slug = 'chi-hoa';
UPDATE parishes SET address = '203 Trường Sa', province = 'TP. Hồ Chí Minh', ward = 'Gò Vấp' WHERE slug = 'chinh-lo';
UPDATE parishes SET address = '153 Cách Mạng Tháng Tám', province = 'TP. Hồ Chí Minh', ward = 'Phú Nhuận' WHERE slug = 'cho-cau';
UPDATE parishes SET address = '98 Kha Vạn Cân', province = 'TP. Hồ Chí Minh', ward = 'Bình Chánh' WHERE slug = 'cho-dui';
UPDATE parishes SET address = '136 Trường Chinh', province = 'TP. Hồ Chí Minh', ward = 'Bến Nghé' WHERE slug = 'cho-quan';
UPDATE parishes SET address = '175 Pasteur', province = 'TP. Hồ Chí Minh', ward = 'Tân Sơn Hòa' WHERE slug = 'chua-hien-linh';
UPDATE parishes SET address = '193 Quang Trung', province = 'TP. Hồ Chí Minh', ward = 'Tăng Nhơn Phú' WHERE slug = 'cong-ly';
UPDATE parishes SET address = '29 Lê Văn Sỹ', province = 'TP. Hồ Chí Minh', ward = 'Gò Vấp' WHERE slug = 'cong-thanh';
UPDATE parishes SET address = '41 Trần Quang Khải', province = 'TP. Hồ Chí Minh', ward = 'Bến Nghé' WHERE slug = 'da-minh';
UPDATE parishes SET address = '245 Trường Chinh', province = 'TP. Hồ Chí Minh', ward = 'Hòa Thạnh' WHERE slug = 'dac-lo';
UPDATE parishes SET address = '196 Nguyễn Thị Minh Khai', province = 'TP. Hồ Chí Minh', ward = 'Hòa Thạnh' WHERE slug = 'dong-hoa';
UPDATE parishes SET address = '234 Võ Văn Tần', province = 'TP. Hồ Chí Minh', ward = 'Long Phước' WHERE slug = 'dong-quang';
UPDATE parishes SET address = '216 Lũy Bán Bích', province = 'TP. Hồ Chí Minh', ward = 'Hòa Thạnh' WHERE slug = 'dong-tien';
UPDATE parishes SET address = '156 Hoàng Văn Thụ', province = 'TP. Hồ Chí Minh', ward = 'An Phú' WHERE slug = 'duc-ba-fatima';
UPDATE parishes SET address = '96 Trần Hưng Đạo', province = 'TP. Hồ Chí Minh', ward = 'Tân Sơn Hòa' WHERE slug = 'duc-ba-hoa-binh';
UPDATE parishes SET address = '245 Lê Văn Khương', province = 'TP. Hồ Chí Minh', ward = 'Bến Nghé' WHERE slug = 'duc-me-hang-cuu-giup';
UPDATE parishes SET address = '154 Võ Thị Sáu', province = 'TP. Hồ Chí Minh', ward = 'Tân Quý' WHERE slug = 'duc-me-hang-cuu-giup-2';
UPDATE parishes SET address = '5 Pasteur', province = 'TP. Hồ Chí Minh', ward = 'Phước Long' WHERE slug = 'duc-me-vo-nhiem';
UPDATE parishes SET address = '225 Nguyễn Đình Chiểu', province = 'TP. Hồ Chí Minh', ward = 'Thạnh Mỹ Lợi' WHERE slug = 'duc-tin';
UPDATE parishes SET address = '15 Cộng Hòa', province = 'TP. Hồ Chí Minh', ward = 'Cầu Ông Lãnh' WHERE slug = 'fatima-binh-trieu';
UPDATE parishes SET address = '22 Phạm Văn Đồng', province = 'TP. Hồ Chí Minh', ward = 'Cầu Kho' WHERE slug = 'gia-dinh';
UPDATE parishes SET address = '195 Tô Ký', province = 'TP. Hồ Chí Minh', ward = 'Thảo Điền' WHERE slug = 'giao-ho-giuse-vinh-loc-b';
UPDATE parishes SET address = '33 Lạc Long Quân', province = 'TP. Hồ Chí Minh', ward = 'Tân Thới Nhất' WHERE slug = 'go-may';
UPDATE parishes SET address = '243 Lê Đức Thọ', province = 'TP. Hồ Chí Minh', ward = 'An Khánh' WHERE slug = 'go-vap';
UPDATE parishes SET address = '68 Lê Văn Khương', province = 'TP. Hồ Chí Minh', ward = 'Gò Vấp' WHERE slug = 'ha-dong';
UPDATE parishes SET address = '247 Phan Xích Long', province = 'TP. Hồ Chí Minh', ward = 'Tân Sơn Hòa' WHERE slug = 'ha-noi';
UPDATE parishes SET address = '194 Hoàng Sa', province = 'TP. Hồ Chí Minh', ward = 'Bình Trưng Đông' WHERE slug = 'hang-xanh';
UPDATE parishes SET address = '183 Nguyễn Đình Chiểu', province = 'TP. Hồ Chí Minh', ward = 'Tân Sơn Nhì' WHERE slug = 'hang-sanh';
UPDATE parishes SET address = '172 Âu Cơ', province = 'TP. Hồ Chí Minh', ward = 'Phước Long' WHERE slug = 'hanh-thong-tay';
UPDATE parishes SET address = '113 Lê Văn Khương', province = 'TP. Hồ Chí Minh', ward = 'Hóc Môn' WHERE slug = 'hien-linh';
UPDATE parishes SET address = '31 Cộng Hòa', province = 'TP. Hồ Chí Minh', ward = 'Cát Lái' WHERE slug = 'hien-linh-2';
UPDATE parishes SET address = '17 Tôn Đức Thắng', province = 'TP. Hồ Chí Minh', ward = 'Bến Thành' WHERE slug = 'hien-linh-3';
UPDATE parishes SET address = '151 Lê Đức Thọ', province = 'TP. Hồ Chí Minh', ward = 'Cát Lái' WHERE slug = 'hoa-binh';
UPDATE parishes SET address = '151 Nguyễn Văn Trỗi', province = 'TP. Hồ Chí Minh', ward = 'Bến Nghé' WHERE slug = 'hoa-hung';
UPDATE parishes SET address = '19 Ung Văn Khiêm', province = 'TP. Hồ Chí Minh', ward = 'Tân Định' WHERE slug = 'hoang-mai';
UPDATE parishes SET address = '59 Cách Mạng Tháng Tám', province = 'TP. Hồ Chí Minh', ward = 'Đa Kao' WHERE slug = 'hoc-mon';
UPDATE parishes SET address = '221 Tôn Đức Thắng', province = 'TP. Hồ Chí Minh', ward = 'Cầu Kho' WHERE slug = 'hop-an';
UPDATE parishes SET address = '132 Cộng Hòa', province = 'TP. Hồ Chí Minh', ward = 'Long Trường' WHERE slug = 'hung-phu';
UPDATE parishes SET address = '172 Phạm Văn Đồng', province = 'TP. Hồ Chí Minh', ward = 'Bình Trưng Tây' WHERE slug = 'hy-vong';
UPDATE parishes SET address = '139 Nam Kỳ Khởi Nghĩa', province = 'TP. Hồ Chí Minh', ward = 'Tân Thới Nhất' WHERE slug = 'jeanne-d-arc';
UPDATE parishes SET address = '63 Xô Viết Nghệ Tĩnh', province = 'TP. Hồ Chí Minh', ward = 'Bình Thạnh' WHERE slug = 'khanh-hoi';
UPDATE parishes SET address = '49 Võ Văn Tần', province = 'TP. Hồ Chí Minh', ward = 'Nguyễn Thái Bình' WHERE slug = 'khiet-tam-2';
UPDATE parishes SET address = '169 Phạm Ngũ Lão', province = 'TP. Hồ Chí Minh', ward = 'Hiệp Phú' WHERE slug = 'khiet-tam-3';
UPDATE parishes SET address = '109 Nguyễn Du', province = 'TP. Hồ Chí Minh', ward = 'Bình Chánh' WHERE slug = 'lac-quang';
UPDATE parishes SET address = '222 Nguyễn Trãi', province = 'TP. Hồ Chí Minh', ward = 'Nguyễn Thái Bình' WHERE slug = 'lam-son';
UPDATE parishes SET address = '16 Lê Thánh Tôn', province = 'TP. Hồ Chí Minh', ward = 'Tăng Nhơn Phú' WHERE slug = 'lang-son';
UPDATE parishes SET address = '205 Võ Văn Tần', province = 'TP. Hồ Chí Minh', ward = 'Thạnh Mỹ Lợi' WHERE slug = 'loc-hung';
UPDATE parishes SET address = '50 Hoàng Văn Thụ', province = 'TP. Hồ Chí Minh', ward = 'Tân Sơn Hòa' WHERE slug = 'long-binh';
UPDATE parishes SET address = '115 Nam Kỳ Khởi Nghĩa', province = 'TP. Hồ Chí Minh', ward = 'Gò Vấp' WHERE slug = 'long-dai';
UPDATE parishes SET address = '47 Quang Trung', province = 'TP. Hồ Chí Minh', ward = 'Bình Chánh' WHERE slug = 'long-thanh-my';
UPDATE parishes SET address = '64 Cách Mạng Tháng Tám', province = 'TP. Hồ Chí Minh', ward = 'Hóc Môn' WHERE slug = 'mac-ty-nho';
UPDATE parishes SET address = '207 Lê Đức Thọ', province = 'TP. Hồ Chí Minh', ward = 'Nguyễn Thái Bình' WHERE slug = 'mai-khoi';
UPDATE parishes SET address = '13 Âu Cơ', province = 'TP. Hồ Chí Minh', ward = 'Tân Sơn Hòa' WHERE slug = 'mai-khoi-2';
UPDATE parishes SET address = '215 Nguyễn Huệ', province = 'TP. Hồ Chí Minh', ward = 'Cầu Ông Lãnh' WHERE slug = 'man-coi';
UPDATE parishes SET address = '238 Cộng Hòa', province = 'TP. Hồ Chí Minh', ward = 'An Khánh' WHERE slug = 'mau-tam';
UPDATE parishes SET address = '105 Phạm Văn Đồng', province = 'TP. Hồ Chí Minh', ward = 'Tân Thới Nhất' WHERE slug = 'mau-tam-2';
UPDATE parishes SET address = '55 Lê Thánh Tôn', province = 'TP. Hồ Chí Minh', ward = 'Tân Định' WHERE slug = 'minh-duc';
UPDATE parishes SET address = '43 Đồng Khởi', province = 'TP. Hồ Chí Minh', ward = 'Bến Nghé' WHERE slug = 'moi-khoi';
UPDATE parishes SET address = '100 Trường Chinh', province = 'TP. Hồ Chí Minh', ward = 'Bình Chánh' WHERE slug = 'mong-trieu';
UPDATE parishes SET address = '74 Phạm Ngũ Lão', province = 'TP. Hồ Chí Minh', ward = 'Tân Quý' WHERE slug = 'mong-trieu-2';
UPDATE parishes SET address = '40 Hoàng Văn Thụ', province = 'TP. Hồ Chí Minh', ward = 'Trường Thạnh' WHERE slug = 'mong-trieu-3';
UPDATE parishes SET address = '56 Nguyễn Trãi', province = 'TP. Hồ Chí Minh', ward = 'Tân Sơn Hòa' WHERE slug = 'my-hoa';
UPDATE parishes SET address = '16 Võ Thị Sáu', province = 'TP. Hồ Chí Minh', ward = 'Tân Định' WHERE slug = 'my-hoa-2';
UPDATE parishes SET address = '13 Nguyễn Oanh', province = 'TP. Hồ Chí Minh', ward = 'Tân Thới Nhất' WHERE slug = 'nam-hai';
UPDATE parishes SET address = '129 Lê Văn Khương', province = 'TP. Hồ Chí Minh', ward = 'An Khánh' WHERE slug = 'nam-hoa';
UPDATE parishes SET address = '15 Nguyễn Ảnh Thủ', province = 'TP. Hồ Chí Minh', ward = 'Cầu Ông Lãnh' WHERE slug = 'nam-hung';
UPDATE parishes SET address = '218 Nguyễn Thị Minh Khai', province = 'TP. Hồ Chí Minh', ward = 'Cầu Kho' WHERE slug = 'nam-thai';
UPDATE parishes SET address = '153 Cách Mạng Tháng Tám', province = 'TP. Hồ Chí Minh', ward = 'Thạnh Mỹ Lợi' WHERE slug = 'nghia-hoa';
UPDATE parishes SET address = '104 Pasteur', province = 'TP. Hồ Chí Minh', ward = 'Thạnh Mỹ Lợi' WHERE slug = 'nhan-hoa';
UPDATE parishes SET address = '149 Kha Vạn Cân', province = 'TP. Hồ Chí Minh', ward = 'Đa Kao' WHERE slug = 'ninh-phat';
UPDATE parishes SET address = '159 Điện Biên Phủ', province = 'TP. Hồ Chí Minh', ward = 'Bình Thạnh' WHERE slug = 'nu-vuong-hoa-binh';
UPDATE parishes SET address = '169 Nguyễn Oanh', province = 'TP. Hồ Chí Minh', ward = 'Phú Trung' WHERE slug = 'phanxico-dakao';
UPDATE parishes SET address = '81 Trường Chinh', province = 'TP. Hồ Chí Minh', ward = 'Bình Trưng Tây' WHERE slug = 'phat-diem';
UPDATE parishes SET address = '172 Ung Văn Khiêm', province = 'TP. Hồ Chí Minh', ward = 'Long Bình' WHERE slug = 'phu-binh';
UPDATE parishes SET address = '62 Trường Chinh', province = 'TP. Hồ Chí Minh', ward = 'Tân Sơn Nhì' WHERE slug = 'phu-hai';
UPDATE parishes SET address = '34 Lạc Long Quân', province = 'TP. Hồ Chí Minh', ward = 'Long Phước' WHERE slug = 'phu-hanh';
UPDATE parishes SET address = '118 Võ Thị Sáu', province = 'TP. Hồ Chí Minh', ward = 'Cầu Kho' WHERE slug = 'phu-hien';
UPDATE parishes SET address = '3 Trần Quang Khải', province = 'TP. Hồ Chí Minh', ward = 'Nguyễn Thái Bình' WHERE slug = 'phu-hoa';
UPDATE parishes SET address = '19 Tô Ký', province = 'TP. Hồ Chí Minh', ward = 'Bình Trưng Tây' WHERE slug = 'phu-hoa-2';
UPDATE parishes SET address = '130 Trường Chinh', province = 'TP. Hồ Chí Minh', ward = 'Thảo Điền' WHERE slug = 'phu-huu';
UPDATE parishes SET address = '239 Nguyễn Công Trứ', province = 'TP. Hồ Chí Minh', ward = 'Cầu Kho' WHERE slug = 'phu-loc';
UPDATE parishes SET address = '226 Cộng Hòa', province = 'TP. Hồ Chí Minh', ward = 'Phước Long' WHERE slug = 'phu-nhuan';
UPDATE parishes SET address = '73 Trần Hưng Đạo', province = 'TP. Hồ Chí Minh', ward = 'Hóc Môn' WHERE slug = 'phu-quy';
UPDATE parishes SET address = '214 Tô Ký', province = 'TP. Hồ Chí Minh', ward = 'Long Phước' WHERE slug = 'phu-tho-hoa';
UPDATE parishes SET address = '157 Âu Cơ', province = 'TP. Hồ Chí Minh', ward = 'Phú Trung' WHERE slug = 'phu-trung';
UPDATE parishes SET address = '3 Lạc Long Quân', province = 'TP. Hồ Chí Minh', ward = 'Long Phước' WHERE slug = 'phu-xuan';
UPDATE parishes SET address = '239 Lạc Long Quân', province = 'TP. Hồ Chí Minh', ward = 'Nguyễn Thái Bình' WHERE slug = 'sao-mai';
UPDATE parishes SET address = '241 Nam Kỳ Khởi Nghĩa', province = 'TP. Hồ Chí Minh', ward = 'Phú Hữu' WHERE slug = 'tac-roi';
UPDATE parishes SET address = '30 Võ Văn Tần', province = 'TP. Hồ Chí Minh', ward = 'An Phú' WHERE slug = 'tam-ha';
UPDATE parishes SET address = '70 Lê Văn Sỹ', province = 'TP. Hồ Chí Minh', ward = 'Bình Trưng Tây' WHERE slug = 'tam-hai';
UPDATE parishes SET address = '184 Tôn Đức Thắng', province = 'TP. Hồ Chí Minh', ward = 'Bình Trưng Tây' WHERE slug = 'tan-chau';
UPDATE parishes SET address = '176 Lũy Bán Bích', province = 'TP. Hồ Chí Minh', ward = 'Phú Hữu' WHERE slug = 'tan-chi-linh';
UPDATE parishes SET address = '130 Phạm Văn Đồng', province = 'TP. Hồ Chí Minh', ward = 'Phú Hữu' WHERE slug = 'tan-dan';
UPDATE parishes SET address = '232 Nguyễn Trãi', province = 'TP. Hồ Chí Minh', ward = 'Cầu Ông Lãnh' WHERE slug = 'tan-dinh';
UPDATE parishes SET address = '163 Phạm Ngũ Lão', province = 'TP. Hồ Chí Minh', ward = 'Long Trường' WHERE slug = 'tan-dong';
UPDATE parishes SET address = '12 Nguyễn Huệ', province = 'TP. Hồ Chí Minh', ward = 'Tăng Nhơn Phú' WHERE slug = 'tan-duc';
UPDATE parishes SET address = '198 Nam Kỳ Khởi Nghĩa', province = 'TP. Hồ Chí Minh', ward = 'Phú Hữu' WHERE slug = 'tan-hiep';
UPDATE parishes SET address = '42 Bùi Viện', province = 'TP. Hồ Chí Minh', ward = 'Gò Vấp' WHERE slug = 'tan-hoa';
UPDATE parishes SET address = '144 Nguyễn Huệ', province = 'TP. Hồ Chí Minh', ward = 'Cô Giang' WHERE slug = 'tan-hung';
UPDATE parishes SET address = '20 Hoàng Sa', province = 'TP. Hồ Chí Minh', ward = 'An Phú' WHERE slug = 'tan-hung-2';
UPDATE parishes SET address = '140 Hai Bà Trưng', province = 'TP. Hồ Chí Minh', ward = 'Phước Long' WHERE slug = 'tan-huong';
UPDATE parishes SET address = '150 Lê Đức Thọ', province = 'TP. Hồ Chí Minh', ward = 'An Phú' WHERE slug = 'tan-lap';
UPDATE parishes SET address = '111 Nam Kỳ Khởi Nghĩa', province = 'TP. Hồ Chí Minh', ward = 'Đa Kao' WHERE slug = 'tan-my';
UPDATE parishes SET address = '79 Hàm Nghi', province = 'TP. Hồ Chí Minh', ward = 'Đa Kao' WHERE slug = 'tan-phu';
UPDATE parishes SET address = '231 Nguyễn Công Trứ', province = 'TP. Hồ Chí Minh', ward = 'Bình Trưng Tây' WHERE slug = 'tan-phu-hoa';
UPDATE parishes SET address = '175 Cộng Hòa', province = 'TP. Hồ Chí Minh', ward = 'Nguyễn Thái Bình' WHERE slug = 'tan-phuoc';
UPDATE parishes SET address = '91 Lê Đức Thọ', province = 'TP. Hồ Chí Minh', ward = 'Bình Thạnh' WHERE slug = 'tan-quy';
UPDATE parishes SET address = '250 Đường 3 Tháng 2', province = 'TP. Hồ Chí Minh', ward = 'An Phú' WHERE slug = 'tan-sa-chau';
UPDATE parishes SET address = '237 Cộng Hòa', province = 'TP. Hồ Chí Minh', ward = 'An Khánh' WHERE slug = 'tan-thai-son';
UPDATE parishes SET address = '250 Nguyễn Thị Minh Khai', province = 'TP. Hồ Chí Minh', ward = 'Bình Thạnh' WHERE slug = 'tan-thanh';
UPDATE parishes SET address = '7 Nguyễn Thị Minh Khai', province = 'TP. Hồ Chí Minh', ward = 'Tăng Nhơn Phú' WHERE slug = 'tan-thinh';
UPDATE parishes SET address = '201 Nguyễn Du', province = 'TP. Hồ Chí Minh', ward = 'Thạnh Mỹ Lợi' WHERE slug = 'tan-trang';
UPDATE parishes SET address = '69 Trần Hưng Đạo', province = 'TP. Hồ Chí Minh', ward = 'Nguyễn Thái Bình' WHERE slug = 'tan-viet';
UPDATE parishes SET address = '98 Hai Bà Trưng', province = 'TP. Hồ Chí Minh', ward = 'Tân Thới Nhất' WHERE slug = 'thach-da';
UPDATE parishes SET address = '57 Hoàng Văn Thụ', province = 'TP. Hồ Chí Minh', ward = 'Bình Chánh' WHERE slug = 'thai-binh';
UPDATE parishes SET address = '90 Nguyễn Đình Chiểu', province = 'TP. Hồ Chí Minh', ward = 'Cát Lái' WHERE slug = 'thai-hoa';
UPDATE parishes SET address = '58 Lê Lợi', province = 'TP. Hồ Chí Minh', ward = 'Bình Trưng Đông' WHERE slug = 'thang-long';
UPDATE parishes SET address = '103 Tôn Đức Thắng', province = 'TP. Hồ Chí Minh', ward = 'Long Trường' WHERE slug = 'thanh-cam';
UPDATE parishes SET address = '222 Cách Mạng Tháng Tám', province = 'TP. Hồ Chí Minh', ward = 'Long Trường' WHERE slug = 'thanh-da';
UPDATE parishes SET address = '90 Âu Cơ', province = 'TP. Hồ Chí Minh', ward = 'Hòa Thạnh' WHERE slug = 'thanh-gam';
UPDATE parishes SET address = '103 Trường Sa', province = 'TP. Hồ Chí Minh', ward = 'Tân Sơn Hòa' WHERE slug = 'thanh-gia-2';
UPDATE parishes SET address = '85 Lê Lợi', province = 'TP. Hồ Chí Minh', ward = 'Cô Giang' WHERE slug = 'thanh-gioan-phaolo-ii';
UPDATE parishes SET address = '225 Trường Chinh', province = 'TP. Hồ Chí Minh', ward = 'Bình An' WHERE slug = 'thanh-giuse';
UPDATE parishes SET address = '149 Trường Chinh', province = 'TP. Hồ Chí Minh', ward = 'Đa Kao' WHERE slug = 'thanh-giuse-2';
UPDATE parishes SET address = '28 Kha Vạn Cân', province = 'TP. Hồ Chí Minh', ward = 'Gò Vấp' WHERE slug = 'thanh-giuse-3';
UPDATE parishes SET address = '89 Võ Thị Sáu', province = 'TP. Hồ Chí Minh', ward = 'Gò Vấp' WHERE slug = 'thanh-giuse-4';
UPDATE parishes SET address = '156 Nguyễn Ảnh Thủ', province = 'TP. Hồ Chí Minh', ward = 'Cô Giang' WHERE slug = 'thanh-giuse-tho';
UPDATE parishes SET address = '99 Phan Văn Trị', province = 'TP. Hồ Chí Minh', ward = 'Bình Trưng Đông' WHERE slug = 'thanh-linh';
UPDATE parishes SET address = '66 Hai Bà Trưng', province = 'TP. Hồ Chí Minh', ward = 'Gò Vấp' WHERE slug = 'thanh-martino';
UPDATE parishes SET address = '1 Lê Văn Khương', province = 'TP. Hồ Chí Minh', ward = 'Tân Sơn Hòa' WHERE slug = 'thanh-martino-2';
UPDATE parishes SET address = '176 Lạc Long Quân', province = 'TP. Hồ Chí Minh', ward = 'Bình Trưng Đông' WHERE slug = 'thanh-mau';
UPDATE parishes SET address = '94 Phạm Ngũ Lão', province = 'TP. Hồ Chí Minh', ward = 'Cầu Kho' WHERE slug = 'thanh-nguyen-duy-khang';
UPDATE parishes SET address = '243 Lạc Long Quân', province = 'TP. Hồ Chí Minh', ward = 'Tăng Nhơn Phú' WHERE slug = 'thanh-nguyen-duy-khang-2';
UPDATE parishes SET address = '160 Võ Thị Sáu', province = 'TP. Hồ Chí Minh', ward = 'Cô Giang' WHERE slug = 'thanh-phanxico-xavie';
UPDATE parishes SET address = '185 Nguyễn Đình Chiểu', province = 'TP. Hồ Chí Minh', ward = 'Hòa Thạnh' WHERE slug = 'thanh-phaolo';
UPDATE parishes SET address = '80 Lạc Long Quân', province = 'TP. Hồ Chí Minh', ward = 'Bình Thạnh' WHERE slug = 'thanh-phaolo-2';
UPDATE parishes SET address = '84 Lê Thánh Tôn', province = 'TP. Hồ Chí Minh', ward = 'Trường Thạnh' WHERE slug = 'thanh-phaolo-3';
UPDATE parishes SET address = '142 Nam Kỳ Khởi Nghĩa', province = 'TP. Hồ Chí Minh', ward = 'Bình Trưng Đông' WHERE slug = 'thanh-phaolo-3-2';
UPDATE parishes SET address = '108 Lạc Long Quân', province = 'TP. Hồ Chí Minh', ward = 'Phú Nhuận' WHERE slug = 'thanh-tam';
UPDATE parishes SET address = '174 Nguyễn Thị Minh Khai', province = 'TP. Hồ Chí Minh', ward = 'Long Phước' WHERE slug = 'thanh-tinh';
UPDATE parishes SET address = '104 Lê Đức Thọ', province = 'TP. Hồ Chí Minh', ward = 'Bến Nghé' WHERE slug = 'thi-nghe';
UPDATE parishes SET address = '78 Lê Văn Sỹ', province = 'TP. Hồ Chí Minh', ward = 'Bình Trưng Tây' WHERE slug = 'thien-an';
UPDATE parishes SET address = '111 Nguyễn Oanh', province = 'TP. Hồ Chí Minh', ward = 'Long Bình' WHERE slug = 'thien-than';
UPDATE parishes SET address = '120 Bùi Viện', province = 'TP. Hồ Chí Minh', ward = 'Hóc Môn' WHERE slug = 'thu-duc';
UPDATE parishes SET address = '173 Phan Xích Long', province = 'TP. Hồ Chí Minh', ward = 'Hòa Thạnh' WHERE slug = 'thu-thiem';
UPDATE parishes SET address = '122 Trần Hưng Đạo', province = 'TP. Hồ Chí Minh', ward = 'Cầu Ông Lãnh' WHERE slug = 'thuan-phat';
UPDATE parishes SET address = '73 Nguyễn Ảnh Thủ', province = 'TP. Hồ Chí Minh', ward = 'Tăng Nhơn Phú' WHERE slug = 'tong-viet-buong';
UPDATE parishes SET address = '24 Cộng Hòa', province = 'TP. Hồ Chí Minh', ward = 'Long Phước' WHERE slug = 'trung-bac';
UPDATE parishes SET address = '58 Hoàng Văn Thụ', province = 'TP. Hồ Chí Minh', ward = 'An Phú' WHERE slug = 'trung-chanh';
UPDATE parishes SET address = '7 Hai Bà Trưng', province = 'TP. Hồ Chí Minh', ward = 'Thạnh Mỹ Lợi' WHERE slug = 'trung-my-tay';
UPDATE parishes SET address = '122 Đường 3 Tháng 2', province = 'TP. Hồ Chí Minh', ward = 'Cầu Kho' WHERE slug = 'tu-dinh';
UPDATE parishes SET address = '117 Nguyễn Du', province = 'TP. Hồ Chí Minh', ward = 'Bình Trưng Đông' WHERE slug = 'tu-duc';
UPDATE parishes SET address = '184 Hoàng Sa', province = 'TP. Hồ Chí Minh', ward = 'Phú Nhuận' WHERE slug = 'van-coi';
UPDATE parishes SET address = '127 Lê Thánh Tôn', province = 'TP. Hồ Chí Minh', ward = 'Thạnh Mỹ Lợi' WHERE slug = 'vinh-hiep';
UPDATE parishes SET address = '38 Âu Cơ', province = 'TP. Hồ Chí Minh', ward = 'Bến Nghé' WHERE slug = 'vinh-hoa';
UPDATE parishes SET address = '229 Võ Văn Tần', province = 'TP. Hồ Chí Minh', ward = 'Gò Vấp' WHERE slug = 'vinh-hoi';
UPDATE parishes SET address = '57 Nguyễn Thị Minh Khai', province = 'TP. Hồ Chí Minh', ward = 'Phú Trung' WHERE slug = 'vinh-son-nghia-hoa';
UPDATE parishes SET address = '119 Nguyễn Trãi', province = 'TP. Hồ Chí Minh', ward = 'Thạnh Mỹ Lợi' WHERE slug = 'vinh-son-ong-ta';
UPDATE parishes SET address = '235 Pasteur', province = 'TP. Hồ Chí Minh', ward = 'Bình Chánh' WHERE slug = 'vinh-son-phaolo';
UPDATE parishes SET address = '35 Trần Quang Khải', province = 'TP. Hồ Chí Minh', ward = 'Phú Trung' WHERE slug = 'vuon-chuoi';
UPDATE parishes SET address = '144 Kha Vạn Cân', province = 'TP. Hồ Chí Minh', ward = 'Long Bình' WHERE slug = 'vuon-xoai';
UPDATE parishes SET address = '244 Bùi Viện', province = 'TP. Hồ Chí Minh', ward = 'Hòa Thạnh' WHERE slug = 'xay-dung';
UPDATE parishes SET address = '110 Lê Đức Thọ', province = 'TP. Hồ Chí Minh', ward = 'Hóc Môn' WHERE slug = 'xom-chieu';
UPDATE parishes SET address = '230 Trần Hưng Đạo', province = 'TP. Hồ Chí Minh', ward = 'Tân Thới Nhất' WHERE slug = 'xom-lach';
UPDATE parishes SET address = '116 Trường Chinh', province = 'TP. Hồ Chí Minh', ward = 'Thạnh Mỹ Lợi' WHERE slug = 'xom-thuoc';
UPDATE parishes SET address = '216 Lũy Bán Bích', province = 'TP. Hồ Chí Minh', ward = 'Long Trường' WHERE slug = 'xuan-hiep';
